In [1]:
# --- General Imports ---
import pandas as pd
import numpy as np
import sys
from pathlib import Path
# --- Resolving Import Issue ---
notebook_dir = Path.cwd()
src_path = (notebook_dir / ".." / "src" / "pca").resolve()
if str(src_path) not in sys.path:
    sys.path.insert(0, str(src_path))
# --- Importing API Files ---
from pca import PCA

In [2]:
# --- Reading and Repersenting the Dataset --- #
data_frame = pd.read_csv(r'..\data\raw\cancer_data.csv')
index_list=[i for i in range(1,len(data_frame)+1)]
data_frame.index=index_list
raw_data_amount=len(data_frame)
# --- Representing Data ---
data_frame.iloc[:,] #> Showing some part of te dataframe

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
1,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
2,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
3,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
4,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
5,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
566,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
567,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
568,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
569,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [3]:
# --- Changing Values ---
diagnosis_array = data_frame["diagnosis"].to_numpy()
diagnosis_array = np.where(diagnosis_array=='M', -1, +1)
# --- Deleting Irrelevent Column ---
del data_frame["id"]
del data_frame["diagnosis"]
del data_frame["Unnamed: 32"]
# --- Representing Data ---
data_frame.iloc[:,] #> Showing some part of te dataframe

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
2,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
3,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
4,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
5,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
566,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
567,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
568,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
569,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [4]:
# --- Preparing PCA Parameters ---
PCA_model = PCA()
X = data_frame.to_numpy()
data_frame_columns = data_frame.columns
scaled_X = PCA_model.scaler(X)

In [5]:
# --- PCA Report ---
PCA_X_report = PCA_model.fit(scaled_X, orig_features = data_frame_columns, reset_model_values=True)
PCA_X_report

      PCA  Explained Variance Ratio  Cumulative Variance
0    PCA0                  0.442720             0.442720
1    PCA1                  0.189712             0.632432
2    PCA2                  0.093932             0.726364
3    PCA3                  0.066021             0.792385
4    PCA4                  0.054958             0.847343
5    PCA5                  0.040245             0.887588
6    PCA6                  0.022507             0.910095
7    PCA7                  0.015887             0.925983
8    PCA8                  0.013896             0.939879
9    PCA9                  0.011690             0.951569
10  PCA10                  0.009797             0.961366
11  PCA11                  0.008705             0.970071
12  PCA12                  0.008045             0.978117
13  PCA13                  0.005234             0.983350
14  PCA14                  0.003138             0.986488
15  PCA15                  0.002662             0.989150
16  PCA16                  0.001980             0.991130
17  PCA17                  0.001754             0.992884
18  PCA18                  0.001649             0.994533
19  PCA19                  0.001039             0.995572
20  PCA20                  0.000999             0.996571
21  PCA21                  0.000915             0.997486
22  PCA22                  0.000811             0.998297
23  PCA23                  0.000602             0.998899
24  PCA24                  0.000516             0.999415
25  PCA25                  0.000273             0.999688
26  PCA26                  0.000230             0.999918
27  PCA27                  0.000053             0.999971
28  PCA28                  0.000025             0.999996
29  PCA29                  0.000004             1.000000

In [6]:
# --- Initiating PCA ---
PCA_data_frame = PCA_model.transform(scaled_X, 10)
PCA_data_frame

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10
0,-9.192837,1.948583,1.123166,-3.633731,-1.195110,-1.411424,-2.159370,-0.398407,0.157118,0.877402
1,-2.387802,-3.768172,0.529293,-1.118264,0.621775,-0.028656,-0.013358,0.240988,0.711905,-1.106995
2,-5.733896,-1.075174,0.551748,-0.912083,-0.177086,-0.541452,0.668166,0.097374,-0.024066,-0.454275
3,-7.122953,10.275589,3.232790,-0.152547,-2.960878,-3.053422,-1.429911,1.059565,1.405440,1.116975
4,-3.935302,-1.948072,-1.389767,-2.940639,0.546747,1.226495,0.936213,0.636376,0.263805,-0.377704
...,...,...,...,...,...,...,...,...,...,...
564,-6.439315,-3.576817,-2.459487,-1.177314,-0.074824,2.375193,0.596130,-0.035471,-0.987929,-0.256989
565,-3.793382,-3.584048,-2.088476,2.506028,-0.510723,0.246710,0.716326,-1.113360,0.105207,0.108632
566,-1.256179,-1.902297,-0.562731,2.089227,1.809991,0.534447,0.192758,0.341887,-0.393917,-0.520877
567,-10.374794,1.672010,1.877029,2.356031,-0.033742,-0.567936,-0.223082,-0.280239,0.542035,0.089296
568,5.475243,-0.670637,-1.490443,2.299157,-0.184703,-1.617837,-1.698952,1.046354,-0.374101,0.047726

In [7]:
# --- Saving Processed Data ---
PCA_data_frame.to_csv(r'..\\data\\processed\\processed_and_PCA_transformed_X.csv', index=False)
np.save(r'..\\data\\processed\\processed_and_SVM_encoded_Y', diagnosis_array)
PCA_model.save_info(r"..\\data\\pca\\pca_data")