# --- Data Cleaning & Engineering ---

In [1]:
# --- General Imports ---
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

## > Breast Cancer Dataset

In [2]:
# --- Reading and Repersenting the Dataset --- #
cancer_dataset_df = pd.read_csv(r'..\\data\\raw\\breast_cancer_dataset.csv')
# --- Checking for NaN Values ---
if len(cancer_dataset_df) == len(cancer_dataset_df.dropna()):
    print("The Dataset Has No NaN Values")
else:
    print("Dataset Needs Cleaning")
# --- Representing Data ---
cancer_dataset_df.iloc[:,] #> Showing some part of te dataframe

Dataset Needs Cleaning

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [3]:
# --- Changing Values ---
diagnosis_array = cancer_dataset_df["diagnosis"].to_numpy().astype(str)
cancer_results_y_array = np.where(diagnosis_array=='B', +1, -1)
# --- Cleaning Up ---
del cancer_dataset_df["id"], cancer_dataset_df["Unnamed: 32"], cancer_dataset_df["diagnosis"]
del diagnosis_array
# --- Saving ---
np.save(r"..\\data\\processed\\cancer\\processed_cancer_y_array", cancer_results_y_array)
np.save(r"..\\data\\processed\\cancer\\processed_cancer_x_array", cancer_dataset_df.to_numpy())
# --- Cleaning Up ---
del cancer_results_y_array, cancer_dataset_df

## > Ionosphere Dataset

In [4]:
# --- Reading and Repersenting the Dataset --- #
ionosphere_dataset_df = pd.read_csv(r'..\\data\\raw\\ionosphere_dataset.csv')
# --- Checking for NaN Values ---
if len(ionosphere_dataset_df) == len(ionosphere_dataset_df.dropna()):
    print("The Dataset Has No NaN Values")
else:
    print("Dataset Needs Cleaning")
# --- Representing Data ---
ionosphere_dataset_df.iloc[:,] #> Showing some part of te dataframe

The Dataset Has No NaN Values

,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.1,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
0,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
1,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
2,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
3,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g
4,1,0,0.02337,-0.00592,-0.09924,-0.11949,-0.00763,-0.11824,0.14706,0.06637,...,-0.01535,-0.03240,0.09223,-0.07859,0.00732,0.00000,0.00000,-0.00039,0.12011,b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307,g
346,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712,g
347,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577,g
348,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243,g
349,1,0,0.84710,0.13533,0.73638,-0.06151,0.87873,0.08260,0.88928,-0.09139,...,-0.15114,0.81147,-0.04822,0.78207,-0.00703,0.75747,-0.06678,0.85764,-0.06151,g

In [5]:
# --- Changing Values ---
state_y_array = ionosphere_dataset_df["g"].to_numpy().astype(str)
ionosphere_results_array = np.where(state_y_array=='g', +1, -1)
# --- Cleaning Up ---
del ionosphere_dataset_df["1"], ionosphere_dataset_df["0"], ionosphere_dataset_df["g"]
# --- Saving ---
np.save(r"..\\data\\processed\\ionosphere\\processed_ionosphere_y_array", ionosphere_results_array)
np.save(r"..\\data\\processed\\ionosphere\\processed_ionosphere_x_array", ionosphere_dataset_df.to_numpy())
# --- Cleaning Up ---
del ionosphere_results_array, ionosphere_dataset_df

## > Pima Indians Diabetes Dataset

In [6]:
# --- Reading and Repersenting the Dataset --- #
diabetes_dataset_df = pd.read_csv(r'..\\data\\raw\\pima_indians_diabetes_dataset.csv')
# --- Checking for NaN Values ---
if len(diabetes_dataset_df) == len(diabetes_dataset_df.dropna()):
    print("The Dataset Has No NaN Values")
# --- Representing Data ---
diabetes_dataset_df.iloc[:,] #> Showing some part of te dataframe

The Dataset Has No NaN Values

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [7]:
# --- Changing Values ---
diabetes_results_array = diabetes_dataset_df["Outcome"].to_numpy().astype(str)
diabetes_results_array = np.where(diabetes_results_array=='1', +1, -1)
# --- Cleaning Up ---
del diabetes_dataset_df["Outcome"]
# --- Saving ---
np.save(r"..\\data\\processed\\diabetes\\processed_diabetes_y_array", diabetes_results_array)
np.save(r"..\\data\\processed\\diabetes\\processed_diabetes_x_array", diabetes_dataset_df.to_numpy())
# --- Cleaning Up ---
del diabetes_results_array, diabetes_dataset_df

## > Banknote Authentication Dataset

In [8]:
# --- Reading and Repersenting the Dataset --- #
banknote_dataset_df = pd.read_csv(r'..\\data\\raw\\banknote_authentication_dataset.csv')
# --- Checking for NaN Values ---
if len(banknote_dataset_df) == len(banknote_dataset_df.dropna()):
    print("The Dataset Has No NaN Values")
# --- Representing Data ---
banknote_dataset_df.iloc[:,] #> Showing some part of te dataframe

The Dataset Has No NaN Values

      variance  skewness  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [9]:
# --- Changing Values ---
banknote_results_array = banknote_dataset_df["class"].to_numpy().astype(str)
banknote_results_array = np.where(banknote_results_array=='1', +1, -1)
# --- Cleaning Up ---
del banknote_dataset_df["class"]
# --- Saving ---
np.save(r"..\\data\\processed\\banknote\\processed_banknote_y_array", banknote_results_array)
np.save(r"..\\data\\processed\\banknote\\processed_banknote_x_array", banknote_dataset_df.to_numpy())
# --- Cleaning Up ---
del banknote_results_array, banknote_dataset_df

## > MAGIC Gamma Telescope Dataset

In [10]:
# --- Reading and Repersenting the Dataset --- #
telescope_dataset_df = pd.read_csv(r'..\\data\\raw\\magic_gamma_telescope.csv')
# --- Checking for NaN Values ---
if len(telescope_dataset_df) == len(telescope_dataset_df.dropna()):
    print("The Dataset Has No NaN Values")
# --- Representing Data ---
telescope_dataset_df.iloc[:,] #> Showing some part of te dataframe

The Dataset Has No NaN Values

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
0,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,g
1,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,g
2,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,g
3,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,g
4,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,g
...,...,...,...,...,...,...,...,...,...,...,...
19015,21.3846,10.9170,2.6161,0.5857,0.3934,15.2618,11.5245,2.8766,2.4229,106.8258,h
19016,28.9452,6.7020,2.2672,0.5351,0.2784,37.0816,13.1853,-2.9632,86.7975,247.4560,h
19017,75.4455,47.5305,3.4483,0.1417,0.0549,-9.3561,41.0562,-9.4662,30.2987,256.5166,h
19018,120.5135,76.9018,3.9939,0.0944,0.0683,5.8043,-93.5224,-63.8389,84.6874,408.3166,h
19019,187.1814,53.0014,3.2093,0.2876,0.1539,-167.3125,-168.4558,31.4755,52.7310,272.3174,h

In [11]:
# --- Changing Values ---
telescope_results_array = telescope_dataset_df["class"].to_numpy().astype(str)
telescope_results_array = np.where(telescope_results_array=='g', +1, -1)
# --- Cleaning Up ---
del telescope_dataset_df["class"]
# --- Reducing Dataset's length To Prevent Memory Overload ---
processed_telescope_x_array, _, processed_telescope_y_array, _ = train_test_split(telescope_dataset_df.to_numpy(), telescope_results_array, 
                                                                                  train_size=4000, stratify=telescope_results_array, random_state=42)
# --- Saving ---
np.save(r"..\\data\\processed\\telescope\\processed_telescope_y_array", processed_telescope_y_array)
np.save(r"..\\data\\processed\\telescope\\processed_telescope_x_array", processed_telescope_x_array)
# --- Cleaning Up ---
del telescope_results_array, telescope_dataset_df, processed_telescope_y_array, processed_telescope_x_array